Virtual-Coffee/vc-preptember

preptember-participants.md

⚠️ *We only accept PR with the most checks on the list*
This PR adds Dominic Duffin to the Preptember participants.

Add Dominic to Preptember participants

---

.github/pull_request_template.md

I'm suggesting a rewrite of this sentence as I noticed the grammar wasn't good.

Revised grammar for PR template

---

repositories-list.md

This PR adds BioDrop repository from EddieHubCommunity to the Repositories List.

Add BioDrop to the repositories list

---

preptember-participants.md

This PR adds Christine to the Preptember Participants List.

feat: add my name to preptember-participant list

---

README.md

This PR adds the Preptember walkthrough video to the README
Closes #6

docs: Add Preptember repo walkthrough video

---

preptember-participants.md

Add David Akim to Preptember participants.

Add David to Preptember participants

---

preptember-participants.md

This PR adds teri to the Preptember participants.

Add Teri to Preptember participants

---

preptember-participants.md
repositories-list.md

I added repos as well as my username

feat: add BekahHW to participants and repos to opt in

---

preptember-participants.md

---
---
This PR adds Adam Abundis to the Preptember participants.

Add Adam to Preptember paticipants

---

preptember-participants.md

This PR adds Michael Jolley to the Preptember participants.

Add Michael to Preptember participants

---

preptember-participants.md

---
---
Add Angie's name to Preptember Participants list.

Add Angie to Participants list

---

preptember-participants.md

---
---
This PR adds Anshuman Sathua to the Preptember participants.

Add Anshuman to Preptember participants

---

preptember-participants.md

Added cris crawford

---

repositories-list.md

---
---
This PR adds Forem to the Repositories List.

Add Forem to the repositories list

---

preptember-participants.md

---
---
"This PR adds Tammy Miller to the Preptember participants"

Add Tammy M to Preptember participants

---

preptember-participants.md
repositories-list.md

---
---
This PR adds Ross Larson to the participants list, and also adds the [Hacktoberfest HOWTO repo](https://github.com/hacktoberfesthowto/howto-blog). This source code auto-deploys to a github pages site: https://hacktoberfesthowto.github.io/

Adds Ross and Hacktoberfest HOWTO

---

preptember-participants.md

Add Christina as a Preptember participant

---

repositories-list.md

Added memory-game to repositories list

---

repositories-list.md

---
---
This PR adds the Tiny Troves of Dev Wisdom repo to the Repositories List.

Add Tiny Troves of Dev Wisdom to the repository list

---

preptember-participants.md

---
---
- [ x] 🌱 Practice Open Source
This PR adds David to the Preptember participants

Add David to Preptember participants, David S on slack

---

preptember-participants.md

---
---
Add Brenna to Preptember participants.

Add Brenna to list of Preptember participants

---

preptember-participants.md
repositories-list.md

added contributor and repo details

---

CONTRIBUTING.md

Merge conflicts are process that often terrifying for beginners.
So, this PR adds a video to walkthrough merge conflicts in the VC-Preptember repo to the `CONTRIBUTING.md`.

Add resolve conflicts video walkthrough

---

.github/pull_request_template.md

This PR adds a request for Slack handle info when contributing to this repo. The purpose is to ease maintainers in confirming memberships.

Add Slack handle info in `pull_request_template.md`

---

.github/ISSUE_TEMPLATE/add_participant.yml
.github/ISSUE_TEMPLATE/add_repository.yml
.github/pull_request_template.md
CONTRIBUTING.md
past-preptembers/preptember-participants-2023.md
past-preptembers/repositories-list-2023.md
preptember-participants-2024.md
repositories-list-2024.md

This PR updates the repository to be ready for the Preptember 2024 with the following changes:
- Adds new issue templates
- Updates the Contributing file
- Updates the PR template
- Archives previous Preptember files

Chore: Prepare the Preptember 2024

---

preptember-participants-2024.md
repositories-list-2024.md

Christine Belzie
> [!Warning]
Closes #41 and #40 
<br>
> [!NOTE]
This PR adds Christine Belzie to the Preptember participants. It also adds LinksHub and Codecademy’s Docs project to the Repositories List.

feat: add my name to the preptember list

---

preptember-participants-2024.md

Micha Rodriguez
> [!Warning]
Closes #44  
<br>
> [!NOTE]
This PR adds Micha to the Preptember participants.

Added myself (Micha) as a Preptember participant

---

preptember-participants-2024.md

Pat Smith
> [!Warning]
Closes #48 
<br>
> [!NOTE]
This PR adds Pat Smith to the Preptember participants.

Added Pat to Preptember participants

---

preptember-participants-2024.md

> [!Warning]
Alicia (Bendz)
[https://github.com/Virtual-Coffee/vc-preptember/issues/52](https://github.com/Virtual-Coffee/vc-preptember/issues/52)
<br>
This PR adds albendz (me) to the Preptember participants

Add albendz to preptember participants

---

preptember-participants-2024.md

> [!Warning]
<br>
> [!NOTE]
This PR adds Silvia Reyes to the Preptember participants

Add Silvia Reyes to Preptember participants

---

preptember-participants-2024.md

David A.
> [!Warning]
Add David Akim as a Preptember Participant #57
<br>
> [!NOTE]
This PR adds David Akim to the Preptember participants

Add David Akim to Preptember participants

---

preptember-participants-2024.md
repositories-list-2024.md

Dominic Duffin
> [!Warning]
Closes #59 
<br>
> [!NOTE]
- Add Dominic Duffin to Preptember participants
- Add Python Turtle Art Canvas to Repositories List

Dominic add 2024

---

preptember-participants-2024.md

Christina Loiacono
> [!Warning]
<br>
> [!NOTE]
Add Christina to Preptember participants

Add Christina to Preptember participants

---

repositories-list-2024.md

Alicia
No issue
<br>
> [!NOTE]
I'm adding a few repos I found that are participating in hacktoberfest 2024 and have open issues tagged for participation.

Add a few repositories participating in Hacktoberfest 2024
